language: go
dist: trusty
sudo: true
env:
    global:
        - TF_VERSION_MAJOR=1
        - TF_VERSION_MINOR=14
        - TF_VERSION_PATCH=0

before_install:
  # Install Python 3.6
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3.6-dev python3.6
  - sudo update-alternatives --install /usr/bin/python3 python3.6 /usr/bin/python3.6 0
  # Install python-pip
  - mkdir /tmp/pip && pushd /tmp/pip
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  - popd
  # Install TensorFlow
  - sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-"$TF_VERSION_MAJOR"."$TF_VERSION_MINOR"."$TF_VERSION_PATCH"-cp36-cp36m-linux_x86_64.whl
  - sudo pip3 install dytb protobuf
  # Install TensorFlow system library
  - curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-""$TF_VERSION_MAJOR"."$TF_VERSION_MINOR"."$TF_VERSION_PATCH"".tar.gz" | sudo tar -C /usr/local -xz
  - sudo ldconfig
  # Get and install TensorFlow Go bindings
  - git clone https://github.com/tensorflow/tensorflow $GOPATH/src/github.com/tensorflow/tensorflow/
  - pushd $GOPATH/src/github.com/tensorflow/tensorflow/tensorflow/go
  - git checkout r"$TF_VERSION_MAJOR"."$TF_VERSION_MINOR"
  - go build
  - popd
  # Install Goveralls
  - go get github.com/mattn/goveralls
  # Build models - used in tests
  - pushd test_models
  - sudo python3 create.py
  - sudo bash freeze_graph.sh
script:
  - $GOPATH/bin/goveralls -service=travis-ci
