language: go
os: linux
dist: focal
env:
    global:
        - TF_VERSION_MAJOR=2
        - TF_VERSION_MINOR=3
        - TF_VERSION_PATCH=1

before_install:
  # Install TensorFlow
  - sudo pip3 install tensorflow=="$TF_VERSION_MAJOR"."$TF_VERSION_MINOR"."$TF_VERSION_PATCH"
  - sudo pip3 install protobuf
  - sudo pip3 install -r test_models/requirements.txt
  # Install TensorFlow system library
  - curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-""$TF_VERSION_MAJOR"."$TF_VERSION_MINOR"."$TF_VERSION_PATCH"".tar.gz" | sudo tar -C /usr/local -xz
  - sudo ldconfig
  # Get and install TensorFlow Go bindings
  # NOTE: we use our own fork with the Go package fixed and go-gettable and usable
  - git clone https://github.com/galeone/tensorflow $GOPATH/src/github.com/tensorflow/tensorflow/
  - pushd $GOPATH/src/github.com/tensorflow/tensorflow/tensorflow/go
  - git checkout r"$TF_VERSION_MAJOR"."$TF_VERSION_MINOR"-go
  - go build
  - popd
  # Install Goveralls
  - go get github.com/mattn/goveralls
  # Build models - used in tests
  - pushd test_models
  - sudo python3 create.py
  - sudo python3 estimator.py
  - popd
script:
  - $GOPATH/bin/goveralls -service=travis-ci
